# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ${{ fromJSON('["ubuntu-latest", "ubuntu-20.04"]')[github.repository != 'daisy-row/wft'] }}
    steps:
      - name: Print
        run: env | sort
